name: Push to Azure Container Registry
on:
  push:
    branches:
      - main

jobs:
  push-to-azure-container-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: gestionconfiguracion.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: docker-compose build

      - name: Push Docker image to Azure Container Registry
        run: |
            docker tag mydemoapp:latest ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/mydemoapp:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/mydemoapp:${{ github.sha }}            

