name: Docker Image en Maven

on:
  push:
    branches: [ maven ]
  pull_request:
    branches: [ maven ]

env:

  TAG: ${{ github.run_number }}
  NAME: ${{ github.token }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Java version
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build Docker Image
        run: |
          docker login --username ddragnell --password ${{ secrets.DOCKER_RUN }} ghcr.io
          docker build . -t ghcr.io/ddragnell/pet-clinic:${{ github.token }} -t ghcr.io/ddragnell/pet-clinic:${{ github.run_number }} 
          docker push ghcr.io/ddragnell/pet-clinic:${{ github.token }}
